import sqlite3
import pandas as pd
import json
from experiment_config import experiment_path

DATASETS = {
    "mesh": {
        "item_table": "ill",
        "item_id_column": "tuple_id",
        "item_name_column": "mesh_term",
        "membership_item_column": "tuple_id",

        "additional_item_columns": {
            "patient_id": "TEXT",
            "term_ui": "TEXT",
            "concept_ui": "TEXT",
            "descriptor_ui": "TEXT",
            "descriptor_name": "TEXT",
            "tree_number": "TEXT",
            "all_tree_numbers": "TEXT",
            "top_category": "TEXT",
            "branch_code": "TEXT",
            "subbranch_code": "TEXT",
            "metadata_json": "TEXT",
            "item_size_bytes": "INTEGER",
            "copy_number": "INTEGER",
        },

        "placements": {
            "round_robin": {"node_output": experiment_path("nodes/mesh/round_robin")},

            "tuple_ilp": {"node_output": experiment_path("nodes/mesh/tuple_ilp")},

            "conflict_locality_ilp": {
                "node_output": experiment_path("nodes/mesh/conflict_locality_ilp")}
        }
    },

    "imdb": {
        "item_table": "title",
        "item_id_column": "title_id",
        "item_name_column": "primary_title",
        "membership_item_column": "title_id",

        "additional_item_columns": {
            "source_title_id": "TEXT",
            "title_type": "TEXT",
            "decade": "TEXT",
            "primary_genre": "TEXT",
            "genres": "TEXT",
            "metadata_json": "TEXT",
            "item_size_bytes": "INTEGER",
            "copy_number": "INTEGER",
        },

        "placements": {
            "round_robin": {"node_output": experiment_path("nodes/imdb/round_robin")},

            "tuple_ilp": {"node_output": experiment_path("nodes/imdb/tuple_ilp")},

            "conflict_locality_ilp": {
                "node_output": experiment_path("nodes/imdb/conflict_locality_ilp")}
        }
    }
}


def search_array(search_term):
    """
    Converts a column string separated by commas into a list.
    """

    if pd.isna(search_term) or search_term == "":
        return []

    return [col.strip() for col in search_term.split(",") if col.strip()]


def create_generated_metadata(item_id, item_name):
    """
    Creates metadata for an item generated by the workload.
    """

    # creates metadata json
    metadata_json = json.dumps({}, ensure_ascii=False, separators=(",", ":"))

    # calculates item size
    item_size_bytes = len((str(item_id) + str(item_name) + metadata_json).encode("utf-8"))

    # returns empty metadata json and current item size
    return {"metadata_json": metadata_json, "item_size_bytes": item_size_bytes}

def select(search, config, node_id, placement_type, table, where=None, parameters=()):
    """
    Executes a SELECT query on a node.
    """

    valid_tables = get_valid_tables(config)
    node_output = get_node_output(config, placement_type)

    if table not in valid_tables:
        raise ValueError(f"Unknown table: {table}")

    search_query = search_array(search)

    if not search_query:
        raise ValueError(f"No columns were specified.")
    
    search_sql = ", ".join(search_query)

    db_path = node_output / f"{node_id}.db"

    if not db_path.exists():
        raise FileNotFoundError(f"Database was not found: {db_path}")

    query = f"SELECT {search_sql} FROM {table}"

    if where:
        query += f" WHERE {where}"

    try:
        with sqlite3.connect(db_path) as conn:
            cur = conn.cursor()
            cur.execute(query, parameters)

            rows = cur.fetchall()

    except sqlite3.Error as error:
        raise RuntimeError(f"Error executing query: {query}") from error

    conn.close()

    return rows


def insert_into_node(item_id, item_name, fragment_ids, node_id, placement_type, config):
    """
    Stores an item and its fragment memberships on a specific node.
    """

    item_table = config["item_table"]
    item_id_column = config["item_id_column"]
    item_name_column = config["item_name_column"]
    membership_item_column = config["membership_item_column"]

    additional_item_columns = list(config.get("additional_item_columns", {}).keys())

    generated_item_data = create_generated_metadata(item_id, item_name)

    item_columns = [item_id_column, item_name_column, *additional_item_columns]

    item_values = [item_id, item_name, *[generated_item_data.get(column_name) 
                                         for column_name in additional_item_columns]]

    # Creates placeholders for all item columns of the new item
    placeholders = ", ".join("?" for _ in item_columns)

    node_output = get_node_output(config, placement_type)
    
    db_path = node_output / f"{node_id}.db"

    if not db_path.exists():
        raise FileNotFoundError(f"Database was not found: {db_path}")

    with sqlite3.connect(db_path) as conn:
        cur = conn.cursor()

        # Stores the item once on this node
        cur.execute(
            f"""
            INSERT INTO {item_table} ({", ".join(item_columns)})
            VALUES ({placeholders})
            """,
            item_values
        )

        inserted_membership = 0

        for fragment_id in fragment_ids:
            # Checks whether fragment is already on this node
            cur.execute(
                """
                SELECT *
                FROM fragments
                WHERE fragment_id = ?
                """,
                (fragment_id,)
            )

            if cur.fetchone() is None:
                raise ValueError(f"Fragment {fragment_id} is not stored on node {node_id}.")

            cur.execute(
                f"""
                INSERT INTO fragment_members(fragment_id, {membership_item_column})
                VALUES (?, ?)
                """,
                (fragment_id, item_id)
            )

            # Increments the stored fragment size for a new membership
            if cur.rowcount == 1:
                inserted_membership += 1
                cur.execute(
                    """
                    UPDATE fragments
                    SET fragment_size = fragment_size + 1
                    WHERE fragment_id = ?
                    """,
                    (fragment_id,)
                )

    conn.close()
    return inserted_membership


def validate_updates(table, updates, config):
    """
    Validates SET clause of an UPDATE query.
    """

    if not updates or not updates.strip():
        raise ValueError("No SET clause was specified for the Update.")

    assignment_array = [assignment.strip() for assignment in updates.split(",")]

    validated = []

    valid_columns = get_valid_columns(config)

    for assignment in assignment_array:
        assignment_part = assignment.split("=")

        if len(assignment_part) != 2:
            raise ValueError(f"Invalid SET assignment: {assignment}")

        column = assignment_part[0].strip()
        placeholders = assignment_part[1].strip()

        if column not in valid_columns[table]:
            raise ValueError(f"Column {column} does not exist in table {table}.")

        if placeholders != "?":
            raise ValueError(f"The SET for {column} does not have a ? placeholder.")

        if column in validated:
            raise ValueError(f"Column {column} was used more than once.")

        validated.append(column)

    normalized_set = ", ".join(f"{column} = ?" for column in validated)

    return normalized_set, len(validated)


def update(node_id, config, placement_type, table, updates, where=None, parameters=()):
    """
    Updates the rows in a node database.
    """

    valid_tables = get_valid_tables(config)

    if table not in valid_tables:
        raise ValueError(f"Unknown table: {table}")

    if not updates:
        raise ValueError(f"No updates were given.")

    validated_set, set_parameter_count = validate_updates(table, updates, config)

    # Counts the placeholders required by WHERE
    if where:
        where_param_count = where.count("?")
    else:
        where_param_count = 0

    expected_param_count = (set_parameter_count + where_param_count)

    if len(parameters) != expected_param_count:
        raise ValueError(f"Received {len(parameters)} parameters, "
                         f"however {expected_param_count} were expected.")

    node_output = get_node_output(config, placement_type)
    db_path = node_output / f"{node_id}.db"

    if not db_path.exists():
        raise FileNotFoundError(f"Database was not found: {db_path}")

    query = f"UPDATE {table} SET {validated_set}"

    if where:
        query += f" WHERE {where}"

    try:
        with sqlite3.connect(db_path) as conn:
            cur = conn.cursor()
            cur.execute(query, parameters)

            updated_rows = cur.rowcount

    except sqlite3.Error as error:
        raise RuntimeError(f"Error with executing query: {query}") from error

    conn.close()
    return updated_rows

def validate_delete(table, where, config):
    """
    Validates DELETE query.
    """

    if not where or not where.strip():
        raise ValueError(f"No WHERE condition was specified.")

    condition_array = [condition.strip() for condition in where.split("AND")]

    validated = []

    valid_columns = get_valid_columns(config)

    for condition in condition_array:
        condition_part = condition.split("=")
        if len(condition_part) != 2:
            raise ValueError(f"Invalid WHERE conditions were given as input: {condition}")

        column = condition_part[0].strip()
        placeholder = condition_part[1].strip()

        if column not in valid_columns[table]:
            raise ValueError(f"Unknown column {column} was found in table {table}")

        if placeholder != "?":
            raise ValueError(f"Condition for column {column} does not"
                             " contain a ? placeholder.")

        validated.append(column)

    normalized_where = " AND ".join(f"{column} = ?"
                                    for column in validated)

    return normalized_where, len(validated)


def delete(node_id, config, placement_type, table, where=None, 
           parameters=(), delete_all=False):
    """
    Deletes rows from a node database.
        
    delete_all:
        Must be set as True if the whole table should be deleted.
    """

    valid_tables = get_valid_tables(config)

    if table not in valid_tables:
        raise ValueError(f"Unknown table: {table}")

    if where:
        validated_where, expected_param_count = (validate_delete(table, where, config))
    else:
        if not delete_all:
            raise ValueError("Deleting without a WHERE condition would remove every row. " \
            "Set delete_all=True if this operation should be allowed.")
        
        validated_where = None
        expected_param_count = 0

    if len(parameters) != expected_param_count:
        raise ValueError(f"Received {len(parameters)} parameters, but "
                         f"{expected_param_count} were expected.")

    node_output = get_node_output(config, placement_type)
    db_path = node_output / f"{node_id}.db"

    if not db_path.exists():
        raise FileNotFoundError(f"Database not found: {db_path}")

    query = f"DELETE FROM {table}"

    if validated_where:
        query += f" WHERE {validated_where}"

    try:
        with sqlite3.connect(db_path) as conn:
            cur = conn.cursor()
            cur.execute(query, parameters)

            deleted_rows = cur.rowcount

    except sqlite3.Error as error:
        raise RuntimeError(f"Error executing query: {query}") from error

    conn.close()
    return deleted_rows

def delete_membership_from_node(fragment_id, item_id, node_id, placement_type, config):
    """
    Deletes a fragment membership from a node and decreases its stored fragment size.
    """

    membership_item_column = config["membership_item_column"]

    node_output = get_node_output(config, placement_type)
    db_path = node_output / f"{node_id}.db"

    if not db_path.exists():
        raise FileNotFoundError(f"Database not found: {db_path}")

    with sqlite3.connect(db_path) as conn:
        cur = conn.cursor()
        cur.execute(
            f"""
            DELETE FROM fragment_members
            WHERE fragment_id = ?
            AND {membership_item_column} = ?
            """,
            (fragment_id, item_id)
        )

        deleted_rows = cur.rowcount

        if deleted_rows == 1:
            cur.execute(
                """
                UPDATE fragments
                SET fragment_size = fragment_size - 1
                WHERE fragment_id = ?
                """,
                (fragment_id,)
            )

    conn.close()
    return deleted_rows


# Helper functions for distributed operations

def get_node_output(config, placement_type):
    """
    Returns node directory for a placement type.
    """
    if placement_type not in config["placements"]:
        raise ValueError(f"Unknown placement type {placement_type}")

    return config["placements"][placement_type]["node_output"]

def get_nodes(config, placement_type):
    """
    Returns all node ids of a placement type
    """

    node_output = get_node_output(config, placement_type)

    if not node_output.exists():
        raise FileNotFoundError(f"Node directory not found: {node_output}")

    # Accepts only database files that match node_"number".db
    node_ids = [
        db_path.stem
        for db_path in node_output.glob("node_*.db")
        # Ensures that the "node_" is followed by digits
        if db_path.stem.replace("node_", "").isdigit()
    ]

    # Sorts node ids according to its id
    return sorted(node_ids, key=lambda node_id: int(node_id.rsplit("_", 1)[-1]))


def get_valid_tables(config):
    """
    Returns all valid tables for a dataset
    """
    return {"fragments", config["item_table"], "fragment_members"}

def get_valid_columns(config):
    """
    Returns all valid columns for each table
    """

    additional_item_columns = set(config.get("additional_item_columns", {}).keys())

    return {"fragments": {
            "fragment_id",
            "scheme",
            "value",
            "fragment_size"
        },

        config["item_table"]: {
            config["item_id_column"],
            config["item_name_column"],
            *additional_item_columns
        },

        "fragment_members": {
            "fragment_id",
            config["membership_item_column"]
        }
    }

def find_item_nodes(item_id, placement_type, config, node_ids=None):
    """
    Returns all nodes storing a specific item
    """

    item_table = config["item_table"]
    item_id_column = config["item_id_column"]

    nodes_array = []

    all_nodes = (
        node_ids
        if node_ids is not None
        else get_nodes(config, placement_type)
    )

    for node_id in all_nodes:
        result = select(
            search=item_id_column,
            config=config,
            node_id=node_id, 
            placement_type=placement_type,
            table=item_table,
            where=f"{item_id_column}=?",
            parameters=(item_id,)
            )

        if result:
            nodes_array.append(node_id)

    return nodes_array

def find_fragment_nodes(fragment_id, placement_type, config, node_ids=None):
    """
    Returns all nodes that store a specific fragment
    """
    nodes_array = []

    all_nodes = (
        node_ids
        if node_ids is not None
        else get_nodes(config, placement_type)
    )

    for node_id in all_nodes:
        result = select(
            search="fragment_id",
            config=config,
            node_id=node_id,
            placement_type=placement_type,
            table="fragments",
            where="fragment_id=?",
            parameters=(fragment_id,)
        )

        if result:
            nodes_array.append(node_id)

    return nodes_array

def find_item_fragments(item_id, placement_type, config, item_nodes=None):
    """
    Returns all fragments containing a specific item
    """
    membership_item_column = config["membership_item_column"]

    # Reuses an existing node lookup to avoid scanning all nodes twice
    if item_nodes is None:
        item_nodes = find_item_nodes(item_id, placement_type, config)

    fragment_ids = set()

    for node_id in item_nodes:
        result = select(
            search="fragment_id",
            config=config,
            node_id=node_id,
            placement_type=placement_type,
            table="fragment_members",
            where=f"{membership_item_column} = ?",
            parameters=(item_id,),
        )

        for row in result:
            fragment_ids.add(row[0])

    return sorted(fragment_ids)


# Distributed operations

def select_fragments(fragment_ids, placement_type, config):
    """
    Executes union of all items in the requested fragments.

    First finds node of each requested fragment.
    Fragments located on the same node are then grouped so that each relevant node
    needs to be queried only once.
    That way execution_nodes represent the nodes involved in the multi-fragment query.
    """

    membership_item_column = config["membership_item_column"]

    # Keeps requested unique fragment ids
    requested_fragments = list(dict.fromkeys(str(fragment_id) for fragment_id in fragment_ids))

    # Multi-fragment queries require at least two distinct fragments
    if len(requested_fragments) < 2:
        raise ValueError("FRAGMENT_SELECT requires at least two different fragments.")

    searched_nodes = get_nodes(config, placement_type)
    fragments_in_node = {}
    fragment_nodes = {}

    # Resolves each requested fragment to its assigned storage node
    for fragment_id in requested_fragments:
        nodes = find_fragment_nodes(
            fragment_id,
            placement_type,
            config,
            node_ids=searched_nodes,
        )

        if len(nodes) != 1:
            raise ValueError(
                f"Fragment {fragment_id} is stored on {len(nodes)} nodes; "
                "Only one assignment is required."
            )

        node_id = nodes[0]
        fragment_nodes[fragment_id] = node_id

        # Groups fragments belonging to the same node
        fragments_in_node.setdefault(node_id, []).append(fragment_id)

    selected_item_ids = set()
    node_output = get_node_output(config, placement_type)

    # Queries fragment-membership table on each affected node
    for node_id, node_fragments in fragments_in_node.items():
        placeholders = ", ".join("?" for _ in node_fragments)
        db_path = node_output / f"{node_id}.db"

        with sqlite3.connect(db_path) as conn:
            cur = conn.cursor()
            cur.execute(
                f"""
                SELECT DISTINCT {membership_item_column}
                FROM fragment_members
                WHERE fragment_id IN ({placeholders})
                """,
                node_fragments,
            )

            selected_item_ids.update(row[0] for row in cur.fetchall())

        conn.close()

    # Collects distinct item IDs returned by all relevant nodes
    execution_nodes = sorted(
        fragments_in_node,
        key=lambda node_id: int(node_id.rsplit("_", 1)[-1]),
    )

    # Sort the execution nodes in a stable numeric order
    return {
        "row_count": len(selected_item_ids),
        "fragment_ids": requested_fragments,
        "fragment_nodes": fragment_nodes,
        "searched_nodes": searched_nodes,
        "execution_nodes": execution_nodes,
        # Retained for compatibility with older evaluation code.
        "contacted_nodes": execution_nodes,
    }

def select_item(item_id, placement_type, config):
    """
    Searches for a specific item in the distributed system
    """
    item_table = config["item_table"]
    item_id_column = config["item_id_column"]

    searched_nodes = get_nodes(config, placement_type)

    item_nodes = find_item_nodes(item_id, placement_type, config, node_ids=searched_nodes)

    fragment_ids = find_item_fragments(item_id, placement_type, config, item_nodes)

    if not item_nodes:
        return {
            "rows": [],
            "contacted_nodes": [],
            "execution_nodes": [],
            "searched_nodes": searched_nodes,
            "available_nodes": [],
            "fragment_ids": []
        }

    # Every available node stores the same item information, so that one node 
    # is sufficient for SELECT
    selected_node = item_nodes[0]

    result = select(
        search="*",
        config=config,
        node_id=selected_node,
        placement_type=placement_type,
        table=item_table,
        where=f"{item_id_column} = ?",
        parameters=(item_id,)
    )
    
    return {"rows": result, "contacted_nodes": [selected_node],  
            "execution_nodes": [selected_node],
            "searched_nodes": searched_nodes, "available_nodes": item_nodes, 
            "fragment_ids": fragment_ids}


def insert_item(item_id, item_name, fragment_ids, placement_type, config):
    """
    Inserts an item into nodes storing its fragments.
    """

    # Groups fragments by their assigned node so that an item is inserted
    # only once when associated fragments share the same node
    fragments_in_node = {}

    searched_nodes = get_nodes(config, placement_type)

    for fragment_id in fragment_ids:
        fragment_nodes = find_fragment_nodes(fragment_id, placement_type, config, 
                                             node_ids=searched_nodes,)

        if not fragment_nodes:
            raise ValueError(f"Fragment {fragment_id} is not stored on any node.")

        node_id = fragment_nodes[0]

        if node_id not in fragments_in_node:
            fragments_in_node[node_id] = []

        fragments_in_node[node_id].append(fragment_id)

    count_inserted_memberships = 0

    for node_id, node_fragments in fragments_in_node.items():
        count_inserted_memberships += insert_into_node(
            item_id=item_id,
            config=config,
            item_name=item_name,
            fragment_ids=node_fragments,
            node_id=node_id,
            placement_type=placement_type
        )

    execution_nodes = list(fragments_in_node.keys())

    return {"inserted_item_id": item_id, "item_name": item_name
            , "inserted_memberships": count_inserted_memberships, 
            "contacted_nodes": execution_nodes,
            "execution_nodes": execution_nodes,
            "searched_nodes": searched_nodes,}


def update_item(item_id, update_item_name, placement_type, config):
    """
    Updates an item on every node that stores it.
    """

    item_table = config["item_table"]
    item_id_column = config["item_id_column"]
    item_name_column = config["item_name_column"]

    searched_nodes = get_nodes(config, placement_type)
    item_nodes = find_item_nodes(item_id, placement_type, config, node_ids=searched_nodes)

    updated_rows = 0

    for node_id in item_nodes:
        curr_item = select(
            search="metadata_json",
            config=config,
            node_id=node_id,
            placement_type=placement_type,
            table=item_table,
            where=f"{item_id_column} = ?",
            parameters=(item_id,)
        )

        metadata_json = (curr_item[0][0] if curr_item and curr_item[0][0] else "{}")

        # Recalculates the stored size because of the item name change
        item_size_bytes = len((str(item_id) + str(update_item_name) 
                               + metadata_json).encode("utf-8"))

        result = update(
            node_id=node_id,
            config=config,
            placement_type=placement_type,
            table = item_table,
            updates = f"{item_name_column} = ?, "
                        "item_size_bytes = ?",
            where = f"{item_id_column} = ?",
            parameters = (update_item_name, item_size_bytes, item_id)
        )

        updated_rows += result

    return {"updated_rows": updated_rows, "contacted_nodes": item_nodes,
            "execution_nodes": item_nodes, "searched_nodes": searched_nodes}


def delete_item(item_id, placement_type, config):
    """
    Deletes an item and its memberships from every node that stores it.
    """

    item_table = config["item_table"]
    item_id_column = config["item_id_column"]
    membership_item_column = config["membership_item_column"]

    searched_nodes = get_nodes(config, placement_type)
    item_nodes = find_item_nodes(item_id, placement_type, config, node_ids=searched_nodes)

    deleted_rows = 0
    deleted_memberships = 0

    for node_id in item_nodes:
        memberships = select(
            search="fragment_id",
            config=config,
            node_id=node_id,
            placement_type=placement_type,
            table="fragment_members",
            where=f"{membership_item_column} = ?",
            parameters=(item_id,)
        )

        # Deletes the memberships first so that the stored fragment sizes
        # can be updated before the item itself is deleted
        for membership in memberships:
            fragment_id = membership[0]

            deleted_memberships += delete_membership_from_node(
                fragment_id=fragment_id,
                config=config,
                item_id=item_id,
                node_id=node_id,
                placement_type=placement_type
            )

        deleted_rows += delete(
            node_id=node_id,
            config=config,
            placement_type=placement_type,
            table=item_table,
            where= f"{item_id_column} = ?",
            parameters=(item_id,),
        )

    return {"deleted_rows": deleted_rows, "deleted_memberships": deleted_memberships, 
            "contacted_nodes": item_nodes, "execution_nodes": item_nodes, 
            "searched_nodes": searched_nodes}